version: 2

jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "presentation/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:  # ToDo Change to assembleRelease
          name: Assemble Debug
          command: ./gradlew assembleDebug
      - store_artifacts:
           path: presentation/build/outputs/apk
           destination: apk
      - save_cache:
           paths:
              - ~/.gradlew
           key: jars-{{ checksum "build.gradle" }}-{{ checksum  "presentation/build.gradle" }}
  test:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
        JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
           name: Run Tests
           command: ./gradlew lint test
      - store_artifacts:
            path: presentation/build/reports
            destination: reports
      - run:
            name: Save test results
            command: |
                        mkdir -p ~/junit/
                        find . -type f -regex ".*/build/test-results/testDebugUnitTest/.*xml" -exec cp {} ~/junit/ \;
            when: always
      - store_test_results:
            path: ~/junit
            destination: tests
      - store_artifacts:
            path: ~/junit
            destination: tests

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
           - build