version: 2

jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "presentation/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: presentation/build/reports
          destination: reports
      - store_test_results:
          path: tests/build/test-results/testDebugUnitTest/
          destination: test_reports
      - run:  # ToDo Change to assembleRelease
          name: Assemble Debug
          command: ./gradlew assembleDebug
      - store_artifacts:
           path: presentation/build/outputs/apk
           destination: apk
      - save_cache:
           paths:
              - ~/.gradlew
           key: jars-{{ checksum "build.gradle" }}-{{ checksum  "presentation/build.gradle" }}

# Todo Add Workflow